# -*- coding: utf-8 -*-
"""Generate ServiceLib/Resx/ResUI.tr.resx from the English neutral resx."""
import re
from xml.sax.saxutils import escape

TR = {
    "BatchExportURLSuccessfully": "Paylaşım bağlantısı panoya başarıyla aktarıldı",
    "CheckServerSettings": "Geçersiz yapılandırma, lütfen kontrol edin veya yeniden seçin",
    "ConfigurationFormatIncorrect": "Geçersiz yapılandırma biçimi.",
    "CustomServerTips": "Özel yapılandırmanın tamamen kendi ayarlarınıza bağlı olduğunu ve tüm ayarlarla çalışmadığını unutmayın. Sistem proxy'sini kullanmak istiyorsanız lütfen dinleme portunu elle değiştirin.",
    "Downloading": "İndiriliyor...",
    "FailedConversionConfiguration": "Yapılandırma dosyası dönüştürülemedi",
    "FailedGenDefaultConfiguration": "Varsayılan yapılandırma dosyası oluşturulamadı",
    "FailedGetDefaultConfiguration": "Varsayılan yapılandırma alınamadı",
    "FailedImportedCustomServer": "Özel yapılandırma içe aktarılamadı",
    "FailedReadConfiguration": "Yapılandırma dosyası okunamadı",
    "FillCorrectServerPort": "Lütfen doğru port biçimini girin.",
    "FillLocalListeningPort": "Lütfen yerel dinleme portunu girin.",
    "FillPassword": "Lütfen parolayı girin.",
    "FillServerAddress": "Lütfen adresi girin.",
    "FillUUID": "Lütfen kullanıcı kimliğini (UUID) girin.",
    "Incorrectconfiguration": "Bu doğru bir yapılandırma değil, lütfen kontrol edin",
    "InitialConfiguration": "Başlangıç Yapılandırması",
    "IsLatestCore": "{0} {1} zaten güncel.",
    "IsLatestN": "{0} {1} zaten güncel.",
    "LvAddress": "Adres",
    "LvEncryptionMethod": "Güvenlik",
    "LvPort": "Port",
    "LvServiceType": "Tür",
    "LvSubscription": "Abonelik grubu",
    "LvTodayDownloadDataAmount": "Bugünkü indirme trafiği",
    "LvTodayUploadDataAmount": "Bugünkü yükleme trafiği",
    "LvTotalDownloadDataAmount": "Toplam indirme trafiği",
    "LvTotalUploadDataAmount": "Toplam yükleme trafiği",
    "LvTransportProtocol": "Taşıma",
    "MsgDownloadV2rayCoreSuccessfully": "Çekirdek başarıyla indirildi",
    "MsgFailedImportSubscription": "Abonelik içeriği içe aktarılamadı",
    "MsgGetSubscriptionSuccessfully": "Abonelik içeriği başarıyla alındı",
    "MsgNoValidSubscription": "Geçerli abonelik ayarlanmadı",
    "MsgParsingSuccessfully": "{0} başarıyla çözümlendi",
    "MsgStartGettingSubscriptions": "Abonelikler alınmaya başlandı",
    "MsgStartUpdating": "{0} güncellenmeye başlandı...",
    "MsgSubscriptionDecodingFailed": "Geçersiz abonelik içeriği",
    "MsgUnpacking": "Paket açılıyor...",
    "MsgUpdateSubscriptionEnd": "Abonelik güncellemesi sona erdi",
    "MsgUpdateSubscriptionStart": "Abonelik güncellemesi başladı",
    "MsgUpdateV2rayCoreSuccessfully": "Çekirdek başarıyla güncellendi",
    "MsgUpdateV2rayCoreSuccessfullyMore": "Çekirdek başarıyla güncellendi! Servis yeniden başlatılıyor...",
    "NonvmessOrssProtocol": "VMess veya SS protokolü değil",
    "NotFoundCore": "Çekirdek dosyası (dosya adı: {1}) klasörde ({0}) bulunamadı, lütfen indirip klasöre koyun, indirme adresi: {2}",
    "NoValidQRcodeFound": "Tarama tamamlandı, geçerli QR kodu bulunamadı",
    "OperationFailed": "İşlem başarısız oldu, lütfen kontrol edip yeniden deneyin",
    "PleaseFillRemarks": "Lütfen Açıklama (Remarks) alanını doldurun",
    "PleaseSelectEncryption": "Lütfen şifreleme yöntemini seçin",
    "PleaseSelectProtocol": "Lütfen bir protokol seçin",
    "PleaseSelectServer": "Lütfen önce Sunucu'yu seçin",
    "RemoveDuplicateServerResult": "Yinelenen sunucular temizlendi. Eski: {0}, Yeni: {1}.",
    "RemoveServer": "Silmek istediğinizden emin misiniz?",
    "SaveClientConfigurationIn": "İstemci yapılandırma dosyası şuraya kaydedildi: {0}",
    "StartService": "Servis başlatılıyor ({0})...",
    "SuccessfulConfiguration": "Yapılandırma başarılı. {0}",
    "SuccessfullyImportedCustomServer": "Özel yapılandırma başarıyla içe aktarıldı",
    "SuccessfullyImportedServerViaClipboard": "Panodan {0} sunucu içe aktarıldı",
    "SuccessfullyImportedServerViaScan": "Paylaşım bağlantısı başarıyla tarandı ve içe aktarıldı",
    "TestMeOutput": "Gecikme: {0} ms, {1}",
    "OperationSuccess": "İşlem başarılı",
    "PleaseSelectRules": "Lütfen kural seçin",
    "RemoveRules": "Kuralları silmek istediğinizden emin misiniz?",
    "RoutingRuleDetailRequiredTips": "{0}, zorunlu alanlardan biridir.",
    "LvRemarks": "Açıklama",
    "LvUrl": "URL (isteğe bağlı)",
    "LvCount": "Adet",
    "MsgNeedUrl": "Lütfen URL'yi girin",
    "AddBatchRoutingRulesYesNo": "Kurallar eklensin mi? Evet = ekle, Hayır = değiştir.",
    "MsgDownloadGeoFileSuccessfully": "Geo dosyası başarıyla indirildi: {0}",
    "MsgInformationTitle": "Bilgi",
    "LvCustomIcon": "Özel simge",
    "FillCorrectDNSText": "Lütfen doğru özel DNS'i girin",
    "TransportPathTip1": "*ws/http upgrade/xhttp yolu",
    "TransportPathTip2": "*h2 yolu",
    "TransportPathTip3": "*QUIC anahtarı/KCP seed",
    "TransportPathTip4": "gRPC servis adı",
    "TransportRequestHostTip1": "*http hostu, virgülle (,) ayrılmış",
    "TransportRequestHostTip2": "*ws/http upgrade/xhttp hostu",
    "TransportRequestHostTip3": "*h2 hostu, virgülle (,) ayrılmış",
    "TransportRequestHostTip4": "*QUIC güvenliği",
    "TransportHeaderType1": "raw kamuflaj türü",
    "TransportHeaderType2": "kcp kamuflaj türü",
    "TransportHeaderType3": "QUIC kamuflaj türü",
    "TransportHeaderType4": "gRPC modu",
    "LvTLS": "TLS",
    "TransportPathTip5": "*kcp seed",
    "RegisterGlobalHotkeyFailed": "Genel kısayol {0} kaydedilemedi, neden: {1}",
    "RegisterGlobalHotkeySuccessfully": "Genel kısayol {0} başarıyla kaydedildi",
    "AllGroupServers": "Tümü",
    "FillServerAddressCustom": "Yapılandırmayı içe aktarmak için lütfen göz atın",
    "Speedtesting": "Test ediliyor...",
    "LabLAN": "LAN",
    "LabLocal": "Yerel",
    "MsgServerTitle": "Filtrele, çalıştırmak için Enter'a basın",
    "menuCheckUpdate": "Güncellemeyi Kontrol Et",
    "menuClose": "Kapat",
    "menuExit": "Çıkış",
    "menuGlobalHotkeySetting": "Genel Kısayol Ayarı",
    "menuHelp": "Yardım",
    "menuOptionSetting": "Seçenek Ayarı",
    "menuPromotion": "Tanıtım",
    "menuReload": "Yeniden Yükle",
    "menuRoutingSetting": "Yönlendirme Ayarı",
    "menuServers": "Sunucular",
    "menuSetting": "Ayarlar",
    "menuSubGroupUpdate": "Mevcut aboneliği proxy'siz güncelle",
    "menuSubGroupUpdateViaProxy": "Mevcut aboneliği proxy ile güncelle",
    "menuSubscription": "Abonelik Grubu",
    "menuSubSetting": "Abonelik grubu ayarları",
    "menuSubUpdate": "Abonelikleri proxy'siz güncelle",
    "menuSubUpdateViaProxy": "Abonelikleri proxy ile güncelle",
    "menuSystemproxy": "Sistem proxy'si",
    "menuSystemProxyClear": "Sistem proxy'sini temizle",
    "menuSystemProxyNothing": "Sistem proxy'sini değiştirme",
    "menuSystemProxyPac": "PAC modu",
    "menuSystemProxySet": "Sistem proxy'sini ayarla",
    "TbSettingsColor": "Renk",
    "TbSettingsLanguage": "Dil (Yeniden Başlatma)",
    "menuAddServerViaClipboard": "Panodan Paylaşım Bağlantılarını İçe Aktar",
    "menuAddServerViaScan": "Ekrandaki QR kodunu tara",
    "menuCopyServer": "Seçileni kopyala",
    "menuRemoveDuplicateServer": "Yinelenenleri kaldır",
    "menuRemoveServer": "Seçileni sil",
    "menuSetDefaultServer": "Aktif olarak ayarla",
    "menuClearServerStatistics": "Tüm servis istatistiklerini temizle",
    "menuRealPingServer": "Gerçek gecikmeyi test et",
    "menuSortServerResult": "Test sonucuna göre sırala",
    "menuSpeedServer": "İndirme hızını test et",
    "menuTcpingServer": "tcping test et",
    "menuExport2ClientConfig": "Seçileni tam yapılandırma olarak dışa aktar",
    "menuExport2ShareUrl": "Paylaşım Bağlantısını Panoya Aktar",
    "menuAddCustomServer": "Özel yapılandırma ekle",
    "menuAddShadowsocksServer": "[Shadowsocks] Ekle",
    "menuAddSocksServer": "[SOCKS] Ekle",
    "menuAddTrojanServer": "[Trojan] Ekle",
    "menuAddVlessServer": "[VLESS] Ekle",
    "menuAddVmessServer": "[VMess] Ekle",
    "menuSelectAll": "Tümünü seç",
    "menuMsgViewClear": "Tümünü temizle",
    "menuMsgViewCopy": "Kopyala",
    "menuMsgViewCopyAll": "Tümünü kopyala",
    "menuMsgViewSelectAll": "Tümünü seç",
    "menuSubAdd": "Ekle",
    "menuSubDelete": "Sil",
    "menuSubEdit": "Düzenle",
    "menuSubShare": "Paylaş",
    "LvEnabled": "Güncellemeyi etkinleştir",
    "LvSort": "Sırala",
    "LvUserAgent": "User Agent",
    "TbCancel": "İptal",
    "TbConfirm": "Onayla",
    "GbTransport": "Taşıma",
    "TbAddress": "Adres",
    "TbAllowInsecure": "Güvensize İzin Ver",
    "TbAlpn": "ALPN",
    "TbAlterId": "Alter ID",
    "TbFingerprint": "Fingerprint",
    "TbHeaderType": "Kamuflaj türü",
    "TbId": "UUID(id)",
    "TbNetwork": "Taşıma protokolü (network)",
    "TbPath": "Yol",
    "TbPort": "Port",
    "TbRemarks": "Takma ad (remarks)",
    "TbSecurity": "Şifreleme yöntemi (security)",
    "TbSNI": "SNI",
    "TbStreamSecurity": "TLS",
    "TipNetwork": "*Varsayılan değer: raw",
    "TbCoreType": "Çekirdek Türü",
    "TbFlow5": "Flow",
    "TbGUID": "Oluştur",
    "TbId3": "Parola",
    "TbId4": "Parola (İsteğe bağlı)",
    "TbId5": "UUID(id)",
    "TbSecurity3": "Şifreleme",
    "TbSecurity4": "Kullanıcı (İsteğe bağlı)",
    "TbSecurity5": "Şifreleme",
    "TbPreSocksPort": "Socks portu",
    "TipPreSocksPort": "* Bu değer ayarlandığında, hız gösterme gibi işlevler için Xray/sing-box(Tun) ile bir socks servisi başlatılır",
    "TbBrowse": "Gözat",
    "TbEdit": "Düzenle",
    "TbSettingsAdvancedProtocol": "Gelişmiş proxy ayarları, protokol seçimi (isteğe bağlı)",
    "TbSettingsAllowLAN": "LAN'dan bağlantılara izin ver",
    "TbSettingsAutoHideStartup": "Başlangıçta otomatik gizle",
    "TbSettingsAutoUpdateInterval": "Geo dosyaları için otomatik güncelleme aralığı (saat)",
    "TbSettingsCore": "Çekirdek: temel ayarlar",
    "TbCustomDnsRay": "V2ray Özel DNS",
    "TbSettingsCoreKcp": "Çekirdek: KCP ayarları",
    "TbSettingsCoreType": "Çekirdek Türü ayarları",
    "TbSettingsDefAllowInsecure": "Güvensize İzin Ver",
    "TbSettingsDomainStrategy4Freedom": "Freedom çıkışı alan adı stratejisi",
    "TbSettingsEnableAutoAdjustMainLvColWidth": "Abonelik güncellemesinden sonra sütun genişliğini otomatik ayarla",
    "TbSettingsEnableCheckPreReleaseUpdate": "Ön sürümleri kontrol et",
    "TbSettingsException": "İstisna",
    "TbSettingsExceptionTip": "Hariç tutma: Aşağıdakilerle başlayan adresler için proxy kullanma. Girdileri noktalı virgülle (;) ayırın.",
    "TbSettingsDisplayRealTimeSpeed": "Gerçek zamanlı hızı göster (yeniden başlatma gerektirir)",
    "TbSettingsKeepOlderDedupl": "Yinelenenleri temizlerken eski kayıtları koru",
    "TbSettingsLogEnabled": "Günlüğü Etkinleştir",
    "TbSettingsLogLevel": "Günlük Düzeyi",
    "TbSettingsMuxEnabled": "Mux Çoğullamayı Aç",
    "TbSettingsN": "AoGPN ayarları",
    "TbSettingsPass": "Yetki parolası",
    "TbSettingsSetUWP": "Win10 UWP Loopback'i Ayarla",
    "TbSettingsSniffingEnabled": "Sniffing'i Aç",
    "TbSettingsSocksPort": "Karma Port",
    "TbSettingsStartBoot": "Önyüklemede başlat",
    "TbSettingsStatistics": "Trafik istatistiklerini etkinleştir (yeniden başlatma gerektirir)",
    "TbSettingsSubConvert": "Abonelik dönüştürme URL'si",
    "TbSettingsSystemproxy": "Sistem proxy ayarları",
    "TbSettingsTrayMenuServersLimit": "Tepsi sağ tık menüsü görüntüleme sınırı",
    "TbSettingsUdpEnabled": "UDP'yi Etkinleştir",
    "TbSettingsUser": "Yetki kullanıcısı",
    "TbClearSystemProxy": "Sistem proxy'sini temizle",
    "TbDisplayGUI": "GUI'yi Göster",
    "TbGlobalHotkeySetting": "Genel Kısayol Ayarları",
    "TbGlobalHotkeySettingTip": "Klavyeye basarak doğrudan ayarlayın; yeniden başlatmadan sonra etkinleşir",
    "TbNotChangeSystemProxy": "Sistem proxy'sini değiştirme",
    "TbReset": "Sıfırla",
    "TbSetSystemProxy": "Sistem proxy'sini ayarla",
    "TbSystemProxyPac": "PAC modu",
    "menuShareServer": "Paylaş",
    "menuRouting": "Yönlendirme",
    "NotRunAsAdmin": "Yönetici olarak çalışmıyor",
    "RunAsAdmin": "Yönetici Olarak Çalıştır",
    "menuMoveBottom": "En alta taşı",
    "menuMoveDown": "Aşağı",
    "menuMoveTop": "En üste taşı",
    "menuMoveUp": "Yukarı",
    "MsgFilterTitle": "Filtrele, düzenli ifadeleri destekler",
    "menuWebsiteItem": "{0} Web Sitesi",
    "menuRoutingAdvancedAdd": "Ekle",
    "menuRoutingAdvancedImportRules": "Kuralları İçe Aktar",
    "menuRoutingAdvancedRemove": "Seçileni sil",
    "menuRoutingAdvancedSetDefault": "Aktif kural olarak ayarla",
    "TbdomainStrategy": "Alan adı stratejisi",
    "TbRoutingTabRuleList": "Ön Tanımlı Kural Seti Listesi",
    "TbRoutingTips": "*Kuralları virgülle (,) ayırın; gerçek virgül için <COMMA> kullanın; bir kuralı yok saymak için başına # ekleyin",
    "menuImportRulesFromClipboard": "Panodan Kural İçe Aktar",
    "menuImportRulesFromFile": "Dosyadan Kural İçe Aktar",
    "menuImportRulesFromUrl": "Abonelik URL'sinden Kural İçe Aktar",
    "menuRoutingRuleSetting": "Kural Ayarları",
    "menuRuleAdd": "Kural Ekle",
    "menuRuleExportSelected": "Seçili Kuralları Dışa Aktar",
    "menuRuleList": "Kural Listesi",
    "menuRuleRemove": "Kuralı Sil",
    "menuRoutingRuleDetailsSetting": "Yönlendirme Kuralı Ayrıntı Ayarları",
    "TbAutoSort": "Kaydederken alan adı, IP ve işlem otomatik sıralanır",
    "TbRuleobjectDoc": "Kural nesnesi Dokümanı",
    "TbDnsObjectDoc": "Lütfen DNS Nesnesini doldurun; dokümantasyonu görüntülemek için tıklayın",
    "SubUrlTips": "Grup için burayı boş bırakın",
    "TipChangeRouting": "Yönlendirme ayarı değişti",
    "TipChangeSystemProxy": "Sistem proxy ayarı değişti",
    "TbSettingsRouteOnly": "Yalnızca Yönlendirme",
    "TbSettingsNotProxyLocalAddress": "Yerel (intranet) adresler için proxy kullanma",
    "menuMixedTestServer": "Tek tıkla çoklu gecikme ve hız testi (Ctrl+E)",
    "LvTestDelay": "Gecikme (ms)",
    "LvTestSpeed": "Hız (MB/s)",
    "FailedToRunCore": "Çekirdek çalıştırılamadı, lütfen istem bilgisini kontrol edin",
    "LvFilter": "Açıklama düzenli ifade filtresi",
    "TbDisplayLog": "Günlüğü Göster",
    "TbEnableTunAs": "Tun'u Etkinleştir",
    "TbSettingsNewPort4LAN": "LAN için Yeni Port",
    "TbSettingsTunMode": "Tun Modu ayarları",
    "menuMoveToGroup": "Gruba taşı",
    "TbSettingsEnableDragDropSort": "Sunucuları sürükle-bırak ile sıralamayı etkinleştir (yeniden başlatma gerektirir)",
    "TbAutoRefresh": "Otomatik yenile",
    "SpeedtestingSkip": "Testi atla",
    "menuEditServer": "Düzenle",
    "TbSettingsDoubleClick2Activate": "Sunucuya çift tıklamak onu aktif yapar",
    "SpeedtestingCompleted": "Test tamamlandı",
    "TbSettingsDefFingerprint": "Varsayılan TLS fingerprint",
    "TbSettingsDefUserAgent": "User-Agent",
    "TbSettingsDefUserAgentTips": "Bu parametre yalnızca raw/http, ws, gRPC ve xhttp için geçerlidir",
    "TbSettingsCurrentFontFamily": "Yazı tipi ailesi (yeniden başlatma gerektirir)",
    "TbSettingsCurrentFontFamilyTip": "TTF/TTC yazı tipi dosyasını guiFonts dizinine kopyalayın; ayarlar penceresini yeniden açın",
    "TbSettingsSocksPortTip": "Pac portu = +3; Xray API portu = +4; mihomo API portu = +5;",
    "TbSettingsStartBootTip": "Bunu yönetici ayrıcalıklarıyla ayarlayın, başlangıçtan sonra yönetici ayrıcalıkları alınır",
    "TbSettingsFontSize": "Yazı Tipi Boyutu",
    "TbSettingsSpeedTestTimeout": "Hız Testi Tek Zaman Aşımı Değeri",
    "TbSettingsSpeedTestUrl": "Hız Testi URL'si",
    "menuMoveTo": "Yukarı ve aşağı taşı",
    "TbPublicKey": "Açık Anahtar",
    "TbShortId": "Kısa Id",
    "TbSpiderX": "Spider X",
    "TbSettingsEnableHWA": "Donanım hızlandırmayı etkinleştir (yeniden başlatma gerektirir)",
    "SpeedtestingWait": "Bekleniyor...",
    "SpeedtestingPressEscToExit": "Testi sonlandırmak için ESC'ye basın",
    "TipDisplayLog": "Anormal bağlantı kopması olduğunda lütfen kapatın",
    "MsgSkipSubscriptionUpdate": "Güncellemeler etkin değil, bu abonelik atlanıyor",
    "menuRebootAsAdmin": "Yönetici Olarak Yeniden Başlat",
    "LvMoreUrl": "Ek URL'ler, virgülle ayrılmış; abonelik dönüştürme geçersiz olur",
    "SpeedDisplayText": "{0} : {1}/sn↑ | {2}/sn↓",
    "LvAutoUpdateInterval": "Otomatik güncelleme aralığı (dakika)",
    "TbSettingsLogEnabledToFile": "Dosyaya günlük kaydını etkinleştir",
    "LvConvertTarget": "Dönüştürme hedef türü",
    "LvConvertTargetTip": "Dönüştürme gerekmiyorsa boş bırakın",
    "menuDNSSetting": "DNS Ayarları",
    "TbCustomDnsSingbox": "sing-box Özel DNS",
    "TbDnsSingboxObjectDoc": "Lütfen DNS Yapısını doldurun, dokümanı görüntülemek için tıklayın",
    "TbSettingDnsImportDefConfig": "Varsayılan DNS yapılandırmasını içe aktarmak için tıklayın",
    "TbdomainStrategy4Singbox": "sing-box alan adı stratejisi",
    "TbSettingsMux4SboxProtocol": "sing-box Mux Protokolü",
    "TbRoutingRuleProcess": "İşlem (Linux/Windows)",
    "TbRoutingRuleIP": "IP veya IP CIDR",
    "TbRoutingRuleDomain": "Alan adı",
    "menuAddHysteria2Server": "[Hysteria2] Ekle",
    "TbSettingsHysteriaBandwidth": "Hysteria Maks. bant genişliği (Yükleme/İndirme)",
    "TbSettingsUseSystemHosts": "Sistem Hosts Dosyasını Kullan",
    "menuAddTuicServer": "[TUIC] Ekle",
    "TbHeaderType8": "Tıkanıklık kontrolü",
    "TbHttpOutboundHeaders": "HTTP başlıkları",
    "TipHttpOutboundHeaders": "Dize veya dize dizisi değerlerine sahip bir JSON nesnesi olarak özel HTTP çıkış istek başlıkları.",
    "LvPrevProfile": "Önceki proxy açıklaması",
    "LvNextProfile": "Sonraki proxy açıklaması",
    "LvPrevProfileTip": "Sunucu açıklamalarının var olduğundan ve benzersiz olduğundan emin olun",
    "TbSettingsTunAutoRoute": "Otomatik Yönlendirme",
    "TbSettingsTunStrictRoute": "Katı Yönlendirme",
    "TbSettingsTunStack": "Stack",
    "TbMtu": "MTU",
    "TbSettingsEnableIPv6Address": "IPv6 Adresini Etkinleştir",
    "menuAddWireguardServer": "[WireGuard] Ekle",
    "TbPrivateKey": "Özel Anahtar",
    "TbReserved": "Ayrılmış",
    "TbLocalAddress": "Adres (IPv4, IPv6)",
    "TbPath7": "obfs parolası",
    "TbRuleMatchingTips": "(Alan adı veya IP veya İşlem Adı) ve Port ve Protokol ve Giriş Etiketi => Çıkış Etiketi",
    "TbAutoScrollToEnd": "Sona otomatik kaydır",
    "TbSettingsSpeedPingTestUrl": "Hız Ping Testi URL'si",
    "SpeedtestingStop": "Test sonlandırılıyor...",
    "TransportRequestHostTip5": "gRPC Authority",
    "menuAddHttpServer": "[HTTP] Ekle",
    "TbSettingsEnableFragment": "Fragment'ı etkinleştir",
    "TbSettingsFragmentPackets": "Fragment Paketleri",
    "TbSettingsFragmentPacketsTip": "Fragment'lanacak paketler: tlshello (TLS ClientHello) veya 1-1 ile 1-5 (ilk N TCP paketi)",
    "TbSettingsFragmentLength": "Fragment Uzunluğu",
    "TbSettingsFragmentLengthTip": "Bayt cinsinden fragment boyut aralığı (örn. 50-100). İlk değer <= ikinci olmalı. Boş = varsayılan.",
    "TbSettingsFragmentInterval": "Fragment Aralığı",
    "TbSettingsFragmentIntervalTip": "Fragmentlar arası gecikme ms cinsinden (örn. 10-20). Aralık 1-100. İlk değer <= ikinci olmalı. Boş = varsayılan.",
    "TbSettingsFragmentMaxSplit": "Maks. Bölünme",
    "TbSettingsFragmentMaxSplitTip": "Paket başına maksimum fragment sayısı (0-10000, 0 = sınırsız). Yalnızca Xray. Boş = varsayılan.",
    "TbSettingsFragmentFallbackDelay": "Yedek Gecikme",
    "TbSettingsFragmentFallbackDelayTip": "ACK tespiti kullanılamadığında yedek gecikme (örn. 500ms). Yalnızca sing-box. Boş = varsayılan.",
    "FillFragmentParameterError": "Geçersiz aralık biçimi. 'başlangıç-bitiş' kullanın (örn. 50-100).",
    "TbSettingsEnableCacheFile4Sbox": "sing-box için önbellek dosyasını etkinleştir (ruleset dosyaları)",
    "LvCustomRulesetPath4Singbox": "sing-box kural setini özelleştir",
    "NeedRebootTips": "İşlem başarılı. Uygulamayı yeniden başlatmak için ayarlar menüsüne tıklayın.",
    "menuOpenTheFileLocation": "Depolama konumunu aç",
    "TbSorting": "Sıralama",
    "TbSortingChain": "Zincir",
    "TbSortingDefault": "Varsayılan",
    "TbSortingDelay": "Gecikme",
    "TbSortingDownSpeed": "İndirme Hızı",
    "TbSortingDownTraffic": "İndirme Trafiği",
    "TbSortingHost": "Host",
    "TbSortingName": "Ad",
    "TbSortingNetwork": "Network",
    "TbSortingTime": "Zaman",
    "TbSortingType": "Tür",
    "TbSortingUpSpeed": "Yükleme Hızı",
    "TbSortingUpTraffic": "Yükleme Trafiği",
    "TbConnections": "Bağlantılar",
    "menuConnectionClose": "Bağlantıyı Kapat",
    "menuConnectionCloseAll": "Tüm Bağlantıları Kapat",
    "TbProxies": "Proxy'ler",
    "menuRulemode": "Kural modu",
    "menuModeDirect": "Doğrudan",
    "menuModeGlobal": "Global",
    "menuModeNothing": "Değiştirme",
    "menuModeRule": "Kural",
    "menuProxiesDelaytest": "Gecikme Testi",
    "menuProxiesDelaytestPart": "Kısmi Düğüm Gecikme Testi",
    "menuProxiesReload": "Proxy'leri Yenile",
    "menuProxiesSelectActivity": "Aktif düğümü seç",
    "TbSettingsDomainStrategy4Out": "Çıkış için varsayılan alan adı stratejisi",
    "TbSettingsMainGirdOrientation": "Ana yerleşim yönü (yeniden başlatma gerektirir)",
    "TbSettingsDomainDNSAddress": "Çıkış DNS adresi",
    "menuProfileAutofitColumnWidth": "Otomatik sütun genişliği ayarı",
    "menuExport2ShareUrlBase64": "Base64 kodlu Paylaşım Bağlantılarını Panoya Aktar",
    "menuExport2ClientConfigClipboard": "Seçileni tam yapılandırma olarak panoya aktar",
    "menuShowOrHideMainWindow": "Ana pencereyi göster veya gizle",
    "TbPreSocksPort4Sub": "Özel yapılandırma socks portu",
    "menuBackupAndRestore": "Yedekle ve Geri Yükle",
    "menuLocalBackup": "Yerel olarak yedekle",
    "menuLocalRestore": "Yerelden geri yükle",
    "menuRemoteBackup": "Uzak konuma yedekle (WebDAV)",
    "menuRemoteRestore": "Uzaktan geri yükle (WebDAV)",
    "menuLocalBackupAndRestore": "Yerel",
    "menuRemoteBackupAndRestore": "Uzak (WebDAV)",
    "LvWebDavUrl": "WebDAV URL",
    "LvWebDavUserName": "WebDAV Kullanıcı Adı",
    "LvWebDavPassword": "WebDAV Parolası",
    "LvWebDavCheck": "WebDAV Kontrolü",
    "LvWebDavDirName": "Uzak klasör adı (isteğe bağlı)",
    "LocalRestoreInvalidZipTips": "Geçersiz yedekleme dosyası",
    "ConnectionsHostFilterTitle": "Host filtresi",
    "TipActiveServer": "Aktif",
    "TbSettingsGeoFilesSource": "Geo dosyaları kaynağı (isteğe bağlı)",
    "TbSettingsSrsFilesSource": "sing-box ruleset dosyaları kaynağı (isteğe bağlı)",
    "UpgradeAppNotExistTip": "Yükseltme Uygulaması mevcut değil",
    "TbSettingsRoutingRulesSource": "Yönlendirme kuralları kaynağı (isteğe bağlı)",
    "menuRegionalPresets": "Bölgesel ön ayar ayarı",
    "menuRegionalPresetsDefault": "Varsayılan",
    "menuRegionalPresetsRussia": "Rusya",
    "menuRegionalPresetsIran": "İran",
    "TbSettingsChinaUserTip": "Çin bölgesindeki kullanıcılar bu öğeyi yok sayabilir",
    "menuAddServerViaImage": "Görseldeki QR kodunu tara",
    "InvalidUrlTip": "Geçersiz adres (URL)",
    "InsecureUrlProtocol": "Lütfen güvensiz HTTP protokolü abonelik adresi kullanmayın",
    "TbSettingsCurrentFontFamilyLinuxTip": "Yazı tipini sisteme kurun, yazı tipi adını seçin veya yazın, ayarları yeniden başlatın",
    "menuExitTips": "Çıkmak istediğinizden emin misiniz?",
    "LvMemo": "Açıklama Notu",
    "TbSettingsLinuxSudoPassword": "Sistem sudo parolası",
    "TbSettingsLinuxSudoPasswordTip": "Parola komut satırı üzerinden doğrulanır. Doğrulama hatası uygulamanın arızalanmasına neden olursa lütfen uygulamayı yeniden başlatın. Parola saklanmaz ve her yeniden başlatmadan sonra yeniden girilmelidir.",
    "TransportHeaderType5": "xhttp modu",
    "TransportExtraTip": "Ham JSON, biçim: { XHTTP Nesnesi }",
    "TbSettingsHide2TrayWhenClose": "Pencereyi kapatırken tepsiye gizle",
    "TbSettingsMixedConcurrencyCount": "Çoklu test sırasında eşzamanlı test sayısı",
    "TbSettingsExceptionTip2": "Hariç tutma: Aşağıdaki adresler için proxy kullanma. Girdileri virgülle (,) ayırın.",
    "TbSettingsDestOverride": "Sniffing türü",
    "TbSettingsSecondLocalPortEnabled": "İkinci karma portu etkinleştir",
    "TbRoutingInboundTagTips": "tun: TUN girişi, socks: yerel port, socks2: ikinci yerel port, socks3: LAN portu",
    "TbSettingsTheme": "Tema",
    "menuCopyProxyCmdToClipboard": "Proxy komutunu panoya kopyala",
    "SpeedtestingTestFailedPart": "Başarısız kısımlar yeniden test ediliyor, {0} kaldı. Sonlandırmak için ESC'ye basın...",
    "menuTestServerResult": "Test sonucuna göre",
    "menuRemoveInvalidServerResult": "Test sonuçlarına göre geçersizleri kaldır",
    "RemoveInvalidServerResultTip": "{0} geçersiz test sonucu kaldırıldı.",
    "TbPorts7": "Sunucu port aralığı",
    "TbPorts7Tips": "Portu kapsar, virgülle (,) ayırın",
    "menuExportConfig": "Dışa Aktar",
    "TbSettingsIPAPIUrl": "Mevcut bağlantı bilgisi testi URL'si",
    "TbRuleOutboundTagTip": "Sunucu açıklaması yazılabilir, var olduğundan ve benzersiz olduğundan emin olun",
    "SudoIncorrectPasswordTip": "Parola yanlış, lütfen tekrar deneyin.",
    "TbMldsa65Verify": "Mldsa65Verify",
    "menuAddAnytlsServer": "[Anytls] Ekle",
    "TbRemoteDNS": "Uzak DNS",
    "TbDomesticDNS": "Yerel DNS",
    "TbDirectResolveStrategy": "Doğrudan Hedef Çözümleme Stratejisi",
    "TbRemoteResolveStrategy": "Proxy Hedef Çözümleme Stratejisi",
    "TbAddCommonDNSHosts": "Ortak DNS Hostlarını Ekle",
    "TbFakeIP": "FakeIP",
    "TbBlockSVCBHTTPSQueries": "SVCB ve HTTPS Sorgularını Engelle",
    "TbDNSHostsConfig": "DNS Hostları: (satır başına \"alanadı1 ip1 ip2\")",
    "ThBasicDNSSettings": "Temel DNS Ayarları",
    "ThAdvancedDNSSettings": "Gelişmiş DNS Ayarları",
    "TbValidateDirectExpectedIPs": "Bölgesel Alan Adı IP'lerini Doğrula",
    "TbValidateDirectExpectedIPsDesc": "Yapılandırıldığında, bölgesel alan adları için dönen IP'leri doğrular (örn. geosite:cn - geoip:cn), yalnızca beklenen IP'leri döndürür",
    "TbCustomDNSEnable": "Özel DNS'i Etkinleştir",
    "TbCustomDNSEnabledPageInvalid": "Özel DNS Etkin, Bu Sayfanın Ayarları Geçersiz",
    "TbBlockSVCBHTTPSQueriesTips": "Etkinleştirildiğinde ECH ve HTTP/3 kullanılabilirlik kontrollerini engeller",
    "FillCorrectConfigTemplateText": "Lütfen doğru yapılandırma şablonunu doldurun",
    "menuFullConfigTemplate": "Tam Yapılandırma Şablonu Ayarı",
    "TbFullConfigTemplateEnable": "Tam Yapılandırma Şablonunu Etkinleştir",
    "TbRayFullConfigTemplate": "v2ray Tam Yapılandırma Şablonu",
    "TbRayFullConfigTemplateDesc": "Yalnızca Çıkış Yapılandırması Ekle, routing.balancers ve routing.rules.outboundTag, dokümanı görüntülemek için tıklayın",
    "TbAddProxyProtocolOutboundOnly": "Proxy Olmayan Protokol Çıkışı Ekleme",
    "TbSetUpstreamProxyDetour": "Üst Akış Proxy Etiketini Ayarla",
    "TbSBFullConfigTemplate": "sing-box Tam Yapılandırma Şablonu",
    "TbSBFullConfigTemplateDesc": "Yalnızca Çıkış ve Endpoint Yapılandırması Ekle, dokümanı görüntülemek için tıklayın",
    "TbFullConfigTemplateDesc": "Bu özellik ileri düzey kullanıcılar ve özel gereksinimleri olanlar içindir. Etkinleştirildiğinde Çekirdek'in temel ayarlarını, DNS ayarlarını ve yönlendirme ayarlarını yok sayar. Sistem proxy portunun, trafik istatistiklerinin ve diğer ilgili yapılandırmaların doğru ayarlandığından emin olmalısınız — her şey sizin tarafınızdan yapılandırılacaktır.",
    "MsgStartParsingSubscription": "Abonelik içeriği ayrıştırılmaya ve işlenmeye başlandı",
    "TbSelectProfile": "Profil Seç",
    "TbFakeIPTips": "Varsayılan olarak genel uygulanır ve yerleşik FakeIP filtreleme yalnızca sing-box'ta bulunur.",
    "PleaseAddAtLeastOneServer": "Lütfen En Az Bir Sunucu Ekleyin",
    "TbConfigTypePolicyGroup": "Politika Grubu",
    "TbConfigTypeProxyChain": "Proxy Zinciri",
    "TbLeastPing": "En Düşük Gecikme",
    "TbRandom": "Rastgele",
    "TbRoundRobin": "Round Robin",
    "TbLeastLoad": "En Stabil",
    "TbPolicyGroupType": "Politika Grubu Türü",
    "menuAddPolicyGroupServer": "Politika Grubu Ekle",
    "menuAddProxyChainServer": "Proxy Zinciri Ekle",
    "menuAddChildServer": "Alt Öğe Ekle",
    "menuRemoveChildServer": "Alt Öğeyi Kaldır",
    "menuServerList": "Sunucu öğesi 1, abonelik grubundan otomatik ekle",
    "TbFallback": "Yedek",
    "MsgCoreNotSupportNetwork": "Çekirdek '{0}', '{1}' network türünü desteklemiyor",
    "MsgCoreNotSupportProtocolTransport": "Çekirdek '{0}', '{2}' taşıması kullanılırken '{1}' protokolünü desteklemiyor",
    "MsgCoreNotSupportProtocol": "Çekirdek '{0}', '{1}' protokolünü desteklemiyor",
    "MsgInvalidProperty": "{0} özelliği geçersiz, lütfen kontrol edin",
    "MsgNotSupportProtocol": "'{0}' protokolü desteklenmiyor",
    "TbSettingsHide2TrayWhenCloseTip": "Sistemde tepsi işlevi yoksa lütfen etkinleştirmeyin",
    "TbRuleTypeTips": "Yönlendirme ve DNS için ayrı kurallar ayarlayabilir veya ikisine de uygulamak için \"ALL\" seçebilirsiniz",
    "TbRuleType": "Kural Türü",
    "TbBootstrapDNS": "Bootstrap DNS",
    "TbBootstrapDNSTips": "DNS sunucu alan adlarını çözümler, IP gerektirir",
    "menuFastRealPing": "Gerçek gecikmeyi test et",
    "TbPolicyGroupSubChildTip": "Abonelik gruplarından filtrelenmiş sunucuları otomatik ekle",
    "TbCertPinning": "Sertifika Sabitleme",
    "TbCertPinningTips": "Sabitlenmiş sertifika (ikisinden birini doldurun)\nBelirtildiğinde sertifika sabitlenir ve \"Güvensize İzin Ver\" devre dışı bırakılır.\n\n\"Sertifika Al\" işlemi, kendinden imzalı bir sertifika kullanılıyorsa veya sistemde güvenilmeyen/kötü amaçlı bir CA varsa başarısız olabilir.",
    "TbFetchCert": "Sertifikayı Al",
    "TbFetchCertChain": "Sertifika Zincirini Al",
    "ServerNameMustBeValidDomain": "Lütfen geçerli bir alan adı belirleyin",
    "CertNotSet": "Sertifika ayarlanmadı",
    "CertSet": "Sertifika ayarlandı",
    "TbSettingsCustomSystemProxyPacPath": "Özel PAC dosya yolu",
    "TbSettingsCustomSystemProxyScriptPath": "Özel sistem proxy betik dosyası yolu",
    "TbSettingsMacOSShowInDock": "macOS bunu Dock'ta gösterir (yeniden başlatma gerektirir)",
    "menuServerList2": "Sunucu Öğesi 2, kendi kurduklarınızdan seçin ve ekleyin",
    "TbEchConfigList": "EchConfigList",
    "TbVerifyPeerCertByName": "Eş Sertifikayı Ada Göre Doğrula",
    "TbFullCertTips": "Tam sertifika (zincir), PEM biçimi",
    "TbCertSha256Tips": "Sertifika parmak izi (SHA-256)",
    "TbServeStale": "Serve Stale",
    "TbParallelQuery": "Paralel Sorgu",
    "TbDomesticDNSTips": "Varsayılan olarak yalnızca yönlendirme sırasında çözümleme için çağrılır",
    "TbRemoteDNSTips": "Varsayılan olarak yalnızca yönlendirme sırasında çözümleme için çağrılır; uzak sunucunun bu DNS'e ulaşabildiğinden emin olun",
    "TbDirectResolveStrategyTips": "Ayarlanmazsa veya \"AsIs\" ise, DNS çözümleme sistem DNS'ini kullanır; aksi halde dahili DNS modülü kullanılır.",
    "TbRemoteResolveStrategyTips": "Ayarlanmazsa veya \"AsIs\" ise, DNS çözümleme uzak sunucunun DNS'i tarafından yapılır; aksi halde dahili DNS modülü kullanılır.",
    "TbHopInt7": "Port atlama aralığı",
    "menuServerListPreview": "Sunucu öğesi önizlemesi",
    "TbFinalmask": "Finalmask",
    "MsgRoutingRuleOutboundNodeWarning": "Yönlendirme kuralı {0} çıkış düğümü {1} uyarı: {2}",
    "MsgRoutingRuleOutboundNodeError": "Yönlendirme kuralı {0} çıkış düğümü {1} hata: {2}. Yalnızca proxy düğümüne geri dönülüyor.",
    "MsgGroupCycleDependency": "Grup {0}, alt düğüm {1} üzerinde döngüsel bağımlılığa sahip. Bu düğüm atlanıyor.",
    "MsgGroupChildNodeWarning": "Grup {0} alt düğüm {1} uyarı: {2}",
    "MsgGroupChildNodeError": "Grup {0} alt düğüm {1} hata: {2}. Bu düğüm atlanıyor.",
    "MsgGroupChildGroupNodeWarning": "Grup {0} alt grup düğümü {1} uyarı: {2}",
    "MsgGroupChildGroupNodeError": "Grup {0} alt grup düğümü {1} hata: {2}. Bu düğüm atlanıyor.",
    "MsgGroupNoValidChildNode": "Grup {0} geçerli alt düğüme sahip değil.",
    "MsgRoutingRuleEmptyOutboundTag": "Yönlendirme kuralı {0} boş çıkış etiketine sahip. Yalnızca proxy düğümüne geri dönülüyor.",
    "MsgRoutingRuleOutboundNodeNotFound": "Yönlendirme kuralı {0} çıkış düğümü {1} bulunamadı. Yalnızca proxy düğümüne geri dönülüyor.",
    "MsgSubscriptionPrevProfileNotFound": "Abonelik önceki proxy {0} bulunamadı. Atlanıyor.",
    "MsgSubscriptionNextProfileNotFound": "Abonelik sonraki proxy {0} bulunamadı. Atlanıyor.",
    "menuGenGroupServer": "Politika Grubu Oluştur",
    "menuAllServers": "Tüm sunucular",
    "menuGenRegionGroup": "Bölgeye Göre Grupla",
    "menuEditCopy": "Kopyala",
    "menuEditSelectAll": "Tümünü seç",
    "menuEditPaste": "Yapıştır",
    "menuEditFormat": "Biçimlendir",
    "TbUot": "TCP üzerinden UDP",
    "menuAddNaiveServer": "[NaïveProxy] Ekle",
    "TbInsecureConcurrency": "Güvensiz Eşzamanlılık",
    "TbUsername": "Kullanıcı Adı",
    "TbIcmpRoutingPolicy": "ICMP yönlendirme politikası",
    "TbLegacyProtect": "Eski TUN Koruması",
    "TbCamouflageDomain": "Kamuflaj alan adı",
    "TbHost": "Host",
    "TransportExtra": "XHTTP Extra",
    "menuUdpTestServer": "Sunucuların UDP Gecikmesini Test Et",
    "TbSettingsUdpTestUrl": "UDP Test URL'si",
    "TbSettingsSendThrough": "Yerel çıkış adresi (SendThrough)",
    "TbSettingsSendThroughTip": "Çok arayüzlü ortamlar için yerel makinenin IPv4 adresini girin",
    "TbSettingsBindInterface": "Arayüzü Bağla",
    "TbSettingsBindInterfaceTip": "Çok arayüzlü ortamlar için çıkış bağlantılarında kullanılacak arayüz adını girin. Linux/macOS'ta yalnızca TUN modu etkinken çalışır.",
    "TbPreSharedKey": "PreSharedKey",
    "menuExport2InnerUri": "AoGPN Dahili Paylaşım Bağlantısını Panoya Aktar",
    "MsgCheckUpdateHasNewVersion": "{0} için yeni bir sürüm mevcut: {1}",
    "menuCheckOnly": "Yalnızca Kontrol Et",
    "MsgNotSupport": "Desteklenmiyor",
    "LvTestIpInfo": "IP Bilgisi",
    "menuNewUpdate": "Yeni Güncelleme",
    "MsgAllowInsecureDeprecated": "Mevcut düğüm şifresiz bir bağlantı kullanıyor; bu, iletişiminizin otoriter hükümetlerin kontrolündeki ağ aracıları tarafından doğrudan izlenebileceği anlamına gelir. Güvenlik nedeniyle bu tür düğümler Xray-core 26.2.6 veya daha yeni sürümlerle bağlanamaz. Kendi kurduğunuz bir düğümse lütfen TLS veya başka bir güvenli şifreleme etkinleştirin ya da sertifikayı pinSHA256 ile sabitleyin. Bir havalimanı/sağlayıcı düğümüyse teknik yükseltme için lütfen servis sağlayıcınızla iletişime geçin. Sağlayıcı iş birliği yapmayı reddederse kullanıcı güvenliğine öncelik veren bir sağlayıcıya geçmeniz önerilir. Daha fazla bilgi için: https://github.com/AhmetOzbay27/AoGPN/discussions/9460.",
    "TbRouteExcludeAddress": "Yönlendirmeden Hariç Tutulan Adres",
    "TbRouteExcludeAddressTip": "Ayırmak için virgül (,) kullanın.",
    "MsgTunRouteExcludeInvalidAddress": "TUN yönlendirme hariç tutma listesinde geçersiz adres: {0}",
    "MsgOptionsConflict": "{0} ile {1} arasında çakışma",
    "TbEnableFinalFragment": "Son Fragment'ı Etkinleştir",
    "TbEnableFinalFragmentTip": "Paketlerin kuyruğunu daha küçük parçalara böler. Bu, aktarım hızını ve gecikmeyi etkileyebilir.",
    "TbEnabletDnsViaProxy": "Köprü Üzerinden DNS",
    "MsgInsecureConfiguration": "Güvensiz yapılandırma algılandı: AllowInsecure etkin ancak sertifika sağlanmamış. Bu, MITM saldırılarına neden olabilir.",
    "TbHy2RealmUrl": "Realm URL",
    "InvalidHy2RealmUrl": "Geçersiz Realm URL.",
    "InvalidHttpOutboundHeaders": "Lütfen geçerli HTTP istek başlıkları JSON'u girin.",
    "TbHy2RealmUrlTip": "Biçim: realm://<token>@<rendezvous-host>[:port]/<realm-name>?stun=<stun-host>[:port]",
    "TbGeckoPacketSize": "Gecko Paket Boyutu (min/maks)",
    "TbLegacyProtectTip": "Etkinleştirilirse sing-box TUN kullanılır; aksi halde xray TUN kullanılır.",
    "TbRootCertificateProvider": "Kök Sertifika Sağlayıcısı",
    "TbRootCertificateProviderTip": "Yalnızca AoGPN arayüzünün indirmeleri ve ağ istekleri için geçerlidir. Çekirdeğin sertifika doğrulamasını etkilemez.",
    "TbProxyDialResolveStrategy": "Proxy Dial Çözümleme Stratejisi",
    "TbProxyDialResolveStrategyTip": "Önerilmez; yönlendirme döngülerine neden olabilir.",
    "TbEnableHappyEyeballs": "Happy Eyeballs'ı Etkinleştir",
    "TbEnableHappyEyeballsTip": "UseIP Stratejisini gerektirir. Etkinleştirildiğinde IPv4 ve IPv6 bağlantılarını aynı anda dener ve otomatik olarak daha hızlı olan yolu seçer.",
    "TbIpv6Address": "IPv6 Adresi",
    "TbIpv4Address": "IPv4 Adresi",
}

SRC = "AoGPN/ServiceLib/Resx/ResUI.resx"
DST = "AoGPN/ServiceLib/Resx/ResUI.tr.resx"

with open(SRC, "r", encoding="utf-8", newline="") as f:
    text = f.read()

missing = []
for key, val in TR.items():
    pattern = re.compile(
        r'(<data name="%s" xml:space="preserve">\s*<value>)(.*?)(</value>)' % re.escape(key),
        re.DOTALL,
    )
    new_text, n = pattern.subn(lambda m: m.group(1) + escape(val) + m.group(3), text)
    if n == 0:
        missing.append(key)
    else:
        text = new_text

if missing:
    raise SystemExit("MISSING KEYS: %s" % missing)

# ensure every real data entry got translated (parse actual XML, not header comments)
import xml.etree.ElementTree as ET
dst_keys = set(d.get("name") for d in ET.fromstring(text).findall("data"))
untranslated = dst_keys - set(TR)
if untranslated:
    raise SystemExit("UNTRANSLATED KEYS: %s" % sorted(untranslated))

with open(DST, "w", encoding="utf-8", newline="") as f:
    f.write(text)

print("wrote", DST, "with", len(TR), "translated strings")
